### ISSUE TITLE
[add] api 코드 세팅

### ISSUE THREAD

**Issue by unam98** [ddan-dda-ra/ddan-ddan-android-watch#10]
## 💡 Issue

- 필요한 api 관련 코드들을 미리 추가해두는 작업
## 📝 todo

- [x] 메인펫 조회 - /v1/user/me/main-pet 
- [x] 내 정보 조회 - /v1/user/me
- [x] 일일 칼로리 갱신 - /v1/user/me/daily-calorie
