### ISSUE TITLE
[feat] 유저, 펫 정보 api로 받아와서 화면에 바인딩

### ISSUE THREAD

**Issue by unam98** [ddan-dda-ra/ddan-ddan-android-watch#14]
## 💡 Issue

- 유저, 펫 정보 api로 받아와서 화면에 반영
## 📝 todo

- [x] 목표 칼로리 api로 받아와서 수집한 칼로리와 함께 프로그레스바에 반영
- [x] 펫 정보 api로 받아와서 화면에 바인딩
- [x] 칼로리 프로그레스바 화면 수정
